### ISSUE TITLE
Theme change is not working every time

### ISSUE THREAD

**Issue by benja-M-1** [marcelo-ochoa/sqlcl-docker-extension#4] opened 2022-08-29 15:27 UTC
Hi @marcelo-ochoa 👋 

I was trying out the latest version and noticed that, with Docker Desktop in dark mode, the extension starts in light mode from time to time. Not sure it is related fully on #3. I mean, it would maybe prevent the issue to happen. But I was thinking that maybe it has to do with the fact that the extension starts in light mode, then switches dark mode. The first process being not fully started, the second one does not stop it. Which could cause issues.

**Comment by marcelo-ochoa** [comment] 2022-08-29 15:39
@benja-M-1 
   I am just checking again the log of sqlcl container and now I see only with message once I  switching from ligth/dark mode:
`
$ docker logs -f mochoa_sqlcl-docker-extension-desktop-extension-service 

2022/08/29 15:33:09 started ttyd with theme: {"background":"#F4F4F6","foreground":"#27343B","cursor":"#17191E","selection":"#6BC3F3"}
2022/08/29 15:33:34 started ttyd with theme: {"background":"#202C33","foreground":"#FFFFFF","cursor":"#C4D0DA","selection":"#6BC3F3"}
2022/08/29 15:33:57 started ttyd with theme: {"background":"#F4F4F6","foreground":"#27343B","cursor":"#17191E","selection":"#6BC3F3"}
`
   so I can't reproduce issue #3 :(
   Which is the log  on your machine?
   Marcelo.

PD: Note that to avoid unnecessary restarts there is a logic now to avoid that.

**Comment by marcelo-ochoa** [comment] 2022-09-30 16:09
fixed on 22.2.1

**Closed as completed** 2022-09-30 16:08 UTC
